on: [push]
name: Test

jobs:
  phpstan:
    name: phpstan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v2
      - name: Run phpstanx
        uses: php-actions/phpstan@v3
        with:
          directories: src tests
          level: 3
          phpstanVersion: ^0.12